{{- if and (eq (include "seleniumGrid.useKEDA" $) "true") $.Values.autoscaling.patchObjectFinalizers.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with $.Values.autoscaling.patchObjectFinalizers.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    deploymentName: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- with $.Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
    spec:
      activeDeadlineSeconds: {{ $.Values.autoscaling.patchObjectFinalizers.activeDeadlineSeconds }}
      serviceAccountName: {{ template "seleniumGrid.serviceAccount.fullname" $ }}
      serviceAccount: {{ template "seleniumGrid.serviceAccount.fullname" $ }}
      containers:
        - name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
          image: {{ $.Values.global.seleniumGrid.kubectlImage }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              kubectl get ScaledObjects,ScaledJobs -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} -o=json | jq '.metadata.finalizers = null' | kubectl apply -f - || true ;
              kubectl delete ScaledObjects,ScaledJobs -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} --wait || true ;
              kubectl delete hpa -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} --wait || true ;
      restartPolicy: Never
{{- end }}
