{{- if eq (include "seleniumGrid.useKEDA" $) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "seleniumGrid.keda.roleBinding.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    deploymentName: {{ template "seleniumGrid.keda.roleBinding.fullname" $ }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- with $.Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "seleniumGrid.serviceAccount.fullname" $ }}
roleRef:
  kind: Role
  name: {{ template "seleniumGrid.keda.role.fullname" $ }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
