{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "restartOnUpdate": "true"
  name: {{ include "seleniumGrid.tls.fullname" . }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- if .Values.tls.generateTLS }}
  {{- $name := default "SeleniumHQ" .Values.tls.defaultName -}}
  {{- $days := default 365 (.Values.tls.defaultDays | int) -}}
  {{- $cn := ternary .Values.tls.defaultCN .Values.ingress.hostname (empty .Values.ingress.hostname) -}}
  {{- $server := genSelfSignedCert $cn ( default nil .Values.tls.defaultIPList ) ( default nil .Values.tls.defaultSANList ) $days }}
  tls.crt: {{ $server.Cert | b64enc }}
  tls.key: {{ $server.Key | b64enc }}
{{- else }}
  tls.crt: {{ default (.Files.Get (printf "certs/%s.base64" .Values.serverConfigMap.certificateFile) | b64dec) .Values.tls.certificate | b64enc }}
  tls.key: {{ default (.Files.Get (printf "certs/%s.base64" .Values.serverConfigMap.privateKeyFile) | b64dec) .Values.tls.privateKey | b64enc }}
{{- end }}
  {{ .Values.serverConfigMap.privateKeyFile }}: {{ default (.Files.Get (printf "certs/%s.base64" .Values.serverConfigMap.privateKeyFile) | b64dec) .Values.tls.privateKey | b64enc }}
  {{ .Values.serverConfigMap.certificateFile }}: {{ default (.Files.Get (printf "certs/%s.base64" .Values.serverConfigMap.certificateFile) | b64dec) .Values.tls.certificate | b64enc }}
  {{ .Values.serverConfigMap.trustStoreFile }}: {{ default (.Files.Get (printf "certs/%s.base64" .Values.serverConfigMap.trustStoreFile) | b64dec) .Values.tls.trustStore | b64enc }}
{{- end }}
