{{- if .Values.videoRecorder.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seleniumGrid.video.fullname" . }}
data:
{{ (.Files.Glob "configs/video/*").AsConfig | indent 2 }}
{{- if and $.Values.videoRecorder.uploadDestinationPrefix $.Values.videoRecorder.uploader }}
{{ (.Files.Glob (printf "configs/uploader/%s/*" $.Values.videoRecorder.uploader)).AsConfig | indent 2 }}
{{- end }}
{{- end }}
