{{- if .Values.videoRecorder.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seleniumGrid.video.fullname" . }}
data:
{{ (.Files.Glob "configs/recorder/*").AsConfig | indent 2 }}
{{- if and .Values.videoRecorder.uploader.enabled .Values.videoRecorder.uploader.entryPoint }}
{{ .Values.videoRecorder.uploader.entryPointFileName | indent 2 -}}: |
{{ .Values.videoRecorder.uploader.entryPoint | indent 4 }}
{{- else if and .Values.videoRecorder.uploader.enabled (not .Values.videoRecorder.uploader.entryPoint) }}
{{ (.Files.Glob (printf "configs/uploader/%s/*.sh" $.Values.videoRecorder.uploader.name)).AsConfig | indent 2 }}
{{- end }}
{{- end }}
