name: Deploys

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  deploy:
    # Only continue if the commit message has '[deploy]' in it
    # if: contains(toJson(github.event.commits), '[deploy]') == true
    name: Deploy Docker images
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo ::set-env name=BUILD_DATE::$(date '+%Y%m%d')
      - name: Build base image to get Grid version
        run: VERSION="local" BUILD_DATE=${BUILD_DATE} make base
      - name: Get Grid version
        # sed used to remove last comma of Selenium version output
        run: echo ::set-env name=GRID_VERSION::$(docker run --rm selenium/base:local-${BUILD_DATE} java -jar /opt/selenium/selenium-server.jar hub --version | awk '{print $3}' | sed 's/\(.*\),/\1 /')
      - name: Display Grid version
        run: echo ${GRID_VERSION}
      - name: Build images
        run: VERSION="${GRID_VERSION}" BUILD_DATE=${BUILD_DATE} make build
      #      - name: Login Docker Hub
      #        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      #        env:
      #          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      #          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #      - name: Deploy new images
      #        run: VERSION="${TAG}" make release
      - name: Tag browser images
        run: VERSION="${GRID_VERSION}" BUILD_DATE=${BUILD_DATE} PUSH_IMAGE=false make tag_and_push_browser_images
      - name: Get latest tag
        run: echo ::set-env name=LATEST_TAG::$(git tag | tail -1)
      - name: Display latest tag
        run: echo ${LATEST_TAG}
#      - name: Display commits since last tag
#        run: echo $(git log "${LATEST_TAG}...automated-release" --pretty=format:"* [\`%h\`](http://github.com/seleniumhq/docker-selenium/commit/%H) - %s :: %an")
      - name: List images
        run: docker images --filter=reference='selenium/*:*' --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.Size}}"

# Enable this part when Selenium 4 is released
#      - name: Deploy tag latest
#        run: VERSION="${TRAVIS_TAG}" make tag_latest
#      - name: Deploy release latest
#        run: VERSION="${TRAVIS_TAG}" make release_latest
