name: Update Dev/Beta Browser Images

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        browser: [chrome,firefox,edge]
        channel: [dev,beta]
    env:
      NAME: selenium

    steps:
    - uses: actions/checkout@v3
    - name: Setup environment variables
      run: |
        export SELENIUM_VERSION=$(grep selenium-server Base/Dockerfile | sed 's/.*-\([^-]*\)\.jar \\/\1/' | head -n 1)
        echo "SELENIUM_VERSION="$SELENIUM_VERSION >> $GITHUB_ENV
        export BUILD_DATE=$(date '+%Y%m%d')
        echo "BUILD_DATE="$BUILD_DATE >> $GITHUB_ENV

    - name: Temporarily pull node-base as it is faster
      run: |
        docker pull $NAME/node-base:latest
        docker tag $NAME/node-base:latest $NAME/node-base:$CHANNEL
        docker tag $NAME/node-base:latest $NAME/node-base:$CHANNEL
        
    - name: Build the Dev/Beta Docker container images
      env:
        BROWSER: ${{ matrix.browser }}
        CHANNEL: ${{ matrix.channel }}
      run: |
        VERSION=$SELENIUM_VERSION make hub $BROWSER_$CHANNEL standalone_$BROWSER_$CHANNEL
        # Need to check for an older Chromedriver by 1 major version vefore failing.

    - name: Make it easier to test the node dev/beta images by tagging node-base and hub with dev/beta
      run: |
        docker tag $NAME/node-base:$SELENIUM_VERSION-$BUILD_DATE $NAME/node-base:$CHANNEL
        docker tag $NAME/hub:$SELENIUM_VERSION-$BUILD_DATE $NAME/hub:$CHANNEL

    - name: Test the Dev/Beta Docker container images
      run: |
        export NAMESPACE=$NAME
        $BROWSER_CAPS=`node -p "process.argv[1][0].toUpperCase() + process.argv[1].toString().substring(1)"` $BROWSER
        VERSION=$CHANNEL ./tests/bootstrap.sh Node$BROWSER_CAPS
        VERSION=$CHANNEL ./tests/bootstrap.sh Standalone$BROWSER_CAPS
        