name: Update Chart CHANGELOG

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: contains(toJson(github.event.commits), 'Update tag in docs and files') == true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update chart CHANGELOG
        run: ./generate_chart_changelog.sh

      - name: Commit files
        run: |
          git config --local user.email "selenium-ci@users.noreply.github.com"
          git config --local user.name "Selenium CI Bot"
          git commit -m "Update chart CHANGELOG [skip ci]" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SELENIUM_CI_TOKEN }}
          branch: trunk
